use_frameworks!
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AnimableRefresh_Example' do
  pod 'AnimableRefresh', :path => '../'

  target 'AnimableRefresh_Tests' do
    inherit! :search_paths

    
  end
end
